[package]
name = "kvdb"
version = "0.2.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
bincode = "1.3"

[dev-dependencies]
tempfile = "3.10"
serde_json = "1.0"
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"
tokenizers = "0.21"
hf-hub = "0.4"
